spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # En producción: no debe crear ni alterar tablas
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  cache:
    type: ${SPRING_CACHE_TYPE}

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}
      roles: ${SPRING_SECURITY_USER_ROLES}

server:
  port: ${SERVER_PORT}

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
  metrics:
    enable:
      all: true

springdoc:
  enable-validation: true