spring:
  application:
    name: clean-architecture-example

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: ${SPRING_CACHE_TYPE}

  redis:
    time-to-live: 60

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}
      roles: ${SPRING_SECURITY_USER_ROLES}
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

server:
  port: ${SERVER_PORT}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,threaddump
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true

springdoc:
  enable-validation: false
