spring:
  application:
    name: clean-architecture-example

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clean_architecture}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: ${SPRING_CACHE_TYPE:redis}

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:admin}
      password: ${SPRING_SECURITY_USER_PASSWORD:admin123}
      roles: ${SPRING_SECURITY_USER_ROLES:ACTUATOR}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,threaddump
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true

# springdoc:
#   enable-validation: false
