version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres-db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    env_file: .env
    ports:
      - '${REDIS_PORT}:6379'  # Importante: dentro del contenedor Redis SIEMPRE usa 6379
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: clean-architecture-example:latest
    container_name: clean-architecture-example
    env_file: .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      SPRING_CACHE_TYPE: ${SPRING_CACHE_TYPE}
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: ${REDIS_PORT}

      SPRING_SECURITY_USER_NAME: ${SPRING_SECURITY_USER_NAME}
      SPRING_SECURITY_USER_PASSWORD: ${SPRING_SECURITY_USER_PASSWORD}
      SPRING_SECURITY_USER_ROLES: ${SPRING_SECURITY_USER_ROLES}

      SERVER_PORT: ${SERVER_PORT}
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  db-data:
